{\rtf1\ansi\ansicpg936\cocoartf1504\cocoasubrtf830
{\fonttbl\f0\fnil\fcharset0 Monaco;}
{\colortbl;\red255\green255\blue255;\red14\green14\blue14;\red242\green239\blue236;}
{\*\expandedcolortbl;;\cssrgb\c6667\c6667\c6667;\cssrgb\c96078\c94902\c94118;}
\paperw11900\paperh16840\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\sl420\partightenfactor0

\f0\fs32 \cf2 \cb3 \expnd0\expndtw0\kerning0
baseurl: /resume_demo\
}